version: '3'

services:
  db-mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    privileged: true
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_DATA_DIR=/var/opt/mssql/data
     - MSSQL_LOG_DIR=/var/opt/mssql/log
     - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
     - MSSQL_SA_PASSWORD=Password12345
    restart: always
    networks:
     - default
    ports:
      - '1433:1433'
    volumes:
      - sql-server-data:/var/opt/mssql
      - sqlbackup:/var/opt/mssql/backup
      - /c/docker/shared:/usr/shared

networks:
  default:
    driver: bridge

volumes:
  sql-server-data:
    driver: local
  sqlbackup:
